# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/processed_sparse/adjacent/graphs
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/processed_sparse/adjacent/doublets/high_augmented_fullsplit
# n_files: 8600

# Graph building configuration
selection:
    pt_min: 0. # GeV
    n_phi_sections: 8
    threshold: 0.
    embed_feats: False
    augmented: True