# Input/output configuration
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/processed_sparse/adjacent/triplets/high_stitched_002cut_003

# Doublet trainer model
doublet_model_dir: /global/cscratch1/sd/danieltm/ExaTrkX/processed_sparse/results/high_003

# Graph building configuration
include_scores: True
threshold: 0.002
# threshold: 0.0
stitch: True